import Header from "../components/Header";
import NextTopLoader from "nextjs-toploader";
import "./globals.css";
import Footer from "../components/Footer";

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
	viewport: {
		width: "device-width",
		initialScale: 1,
		maximumScale: 1,
	},
};

export default function RootLayout({ children }) {
	return (
		<html lang="en">
			<body>
				<NextTopLoader
					color="#013659"
					shadow="0 0 10px #013659,0 0 5px #013659"
				/>
				<Header />
				{children}
				<Footer />
			</body>
		</html>
	);
}
